version: "3.8"

services:
  one-d-music-node:
    container_name: one-d-music-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - .env
    restart: always
networks:
  shared-network:
    external: true